### ISSUE TITLE
[landrush] Pid file not found. Is the daemon running?

### ISSUE THREAD

**Issue by v6** [phinze/landrush#100]
I added the landrush plugin entry, and that entry alone, to my Vagrantfile. 

When I brought vagrant to a halt, to restart it, I got the following error: 

        nathan@nathan:/media/nathan/e2boxen/vagrant_masterless_salt_provision/examples$ vagrant halt
        ==> default: Attempting graceful shutdown of VM...
            default: Guest communication could not be established! This is usually because
            default: SSH is not running, the authentication information was changed,
            default: or some other networking issue. Vagrant will force halt, if
            default: capable.
        [landrush] Stopping daemon...
        [landrush] Pid file not found. Is the daemon running?

I'm not sure if this is more of a bug report or an explanation request, but I would be willing to make a PR to explain what's going on here more, if need be. 

When reloading vagrant, I was prompted again for my password. 

Upon the next halt I get the following error: 

        [landrush] Stopping daemon...
        [landrush] Pid 5009 is not running. Has daemon crashed?

**Comment by phinze** [comment]
Hmm that doesn't sound great! :confused: 

We upgraded our daemon process dependency in the last release... I'll see if I can reproduce this.

**Comment by phinze** [comment]
Okay hmm couldn't reproduce over here. Does it consistently produce that message for you? Also what's your host platform?

**Comment by v6** [comment]
Host platform is Ubuntu 14.10.

The issue may have been that I modified the Vagrantfile without doing a
vagrant destroy => vagrant up.

I'll let you know once I'm back at work and running the box in question.

**Comment by v6** [comment]
This was only after adding landrush, and it only appeared when shutting down the box. 

Maybe I didn't have the landrush plugin installed into Vagrant when I ran this. 

I'll double check that I'm not wasting your time, here.
