### ISSUE TITLE
vagrant.dev resolves to 127.0.53.53

### ISSUE THREAD

**Issue by bguse** [phinze/landrush#103]
Hi,

since short all my vagrant.dev DNSs Settings are resolved to 127.0.53.53.
Landrush is not the Problem. When i use
```
dig -p 10053 @localhost myhost.vagrant.dev

; <<>> DiG 9.8.3-P1 <<>> -p 10053 @localhost myhost.vagrant.dev
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58971
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;myhost.vagrant.dev.	IN	A

;; ANSWER SECTION:
myhost.vagrant.dev.	0 IN	A	192.168.126.2

;; Query time: 97 msec
;; SERVER: 127.0.0.1#10053(127.0.0.1)
;; WHEN: Wed Mar 18 08:12:13 2015
;; MSG SIZE  rcvd: 64
```

all is perfect. But a 
```
dig  myhost.vagrant.dev

; <<>> DiG 9.8.3-P1 <<>> myhost.vagrant.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49643
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;myhost.vagrant.dev.	IN	A

;; ANSWER SECTION:
myhost.vagrant.dev.	3600 IN	A	127.0.53.53

;; Query time: 56 msec
;; SERVER: 192.168.178.1#53(192.168.178.1)
;; WHEN: Wed Mar 18 08:12:56 2015
;; MSG SIZE  rcvd: 64
```
gives back 127.0.53.53

Its cause the new TopLevel Domains.

```
dig myhost.vagrant.dev TXT +short
"Your DNS configuration needs immediate attention see https://icann.org/namecollision"
```

is there a workaround?

thanks.

**Comment by ezekg** [comment]
Has anybody encountered this issue as well and know of a solution, besides using a different `tld`?

**Comment by phinze** [comment]
I haven't seen this myself, but I can tell you about the mechanism we use to redirect these DNS queries in the hopes that it sheds some light on the problem.

We use the fact that the OS X DNS subsystem reads from `/etc/resolver/${DOMAIN}` to configure domain-specific DNS settings.

You can check `ls /etc/resolver` and `cat /etc/resolver/vagrant.dev` to see how we do this.

It's worth noting that `dig` from the host is a simpler tool, and [does not run through the OS X DNS subsystem](http://apple.stackexchange.com/questions/70579/what-is-the-preferred-method-of-command-line-domain-name-lookup-dns/70583#70583). So `dig` having to be pointed specifically to the local DNS server is actually the behavior I'd expect to see.

Hopefully this helps make things clearer - let me know if there's other unexpected behavior outside of `dig` output that's giving you trouble.

**Comment by babilen** [comment]
`.dev` will soon become a official gTLD (with Google as sole applicant *sigh*) and ICANN uses `127.0.53.53` to alert administrators of this name collision. In short `vagrant.dev` shouldn't be used as default domain anymore by landrush, but be replaced by something else.

See http://icannwiki.com/.dev and 
https://www.icann.org/resources/pages/name-collision-2013-12-06-en#127.0.53.53 for further details.

**Comment by cubranic** [comment]
I see an interesting twist to this problem on a multi-machine Vagrantfile on OS X 10.10.4: the host resolves DNS of individual machines correctly, but guests don't. For example, from the host:
```
host$ ping box-a.vagrant.dev
PING box-a.vagrant.dev (192.168.57.103): 56 data bytes
64 bytes from 192.168.57.103: icmp_seq=0 ttl=64 time=0.506 ms
 ```
vs. in guest "box-b":
```
box-b$ ping box-a.vagrant.dev
PING box-a.vagrant.dev (127.0.53.53) 56(84) bytes of data.
64 bytes from 127.0.53.53: icmp_seq=1 ttl=64 time=0.023 ms
```
(BTW, box-b is pinging itself, I can verify it by ssh-ing from box-b into what it thinks is box-a.)

If I use ".test" as my domainname, instead of "vagrant.dev" (i.e., in my Vagrantfile `config.vm.hostname = 'box-a.test'` and `config.landrush.tld = 'test'`), then the the guests don't see other guests that should be on the same network: i.e., box-b can't ping either "box-a" or "box-a.test", it says "unknown host". It's like landrush isn't setting up the guests correctly. (Tested on a Centos7-based box "puppetlabs/centos-7.0-64-nocm".)

**Comment by cubranic** [comment]
Interestingly, if I switch to an Ubuntu-based box, "ubuntu/trusty64", name resolution from guests works correctly: box-b can ping box-a and vice-versa.

**Comment by bertramn** [comment]
I am running into same issues on OSX

```sh
n$ cat /etc/resolver/vagrant.dev
# Generated by landrush, a vagrant plugin
nameserver 127.0.0.1
port 10053
```
and 

```sh
$ vagrant landrush ls
db.vagrant.dev			    192.168.33.13
13.33.168.192.in-addr.arpa	    db.vagrant.dev
```

Yet in the actual vagrant box I cannot resolve or connect to anything on the outside as everything resolves to 127.0.53.53.

**Comment by fongd** [comment]
I can confirm the same problem on El Capitan. DNS lookup on specific domain names listed by "vagrant landrush ls" works but wildcard entries always return 127.0.53.53.

**Comment by njam** [comment]
Closing in favor of https://github.com/phinze/landrush/issues/118
