### ISSUE TITLE
I don't undestand if landrush is based on dnsmasq or not, on linux system

### ISSUE THREAD

**Issue by harobed** [phinze/landrush#110]
Hi,

in README, I don't undestand if landrush is based on dnsmasq or not, on linux system.

In source code, I see many call to iptables.

Can you append some lines in Readme about landrush internal working ?

**Comment by phinze** [comment]
Sure - will do. But quickly here: `landrush` boots a tiny internal `rubydns` forwarding server listening on `10053`, and the `iptables` calls redirect guest traffic to it.

**Comment by harobed** [comment]
When I execute iptables -L, it's free 

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination 
```

How can I say to landrush to reconfigure iptables ?

**Comment by ahpook** [comment]
@harobed you have to use `iptables -t nat -L`; the default is to show the "filter" table which does not represent the NAT rules.

**Comment by harobed** [comment]
```
 sudo iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
```

**Comment by harobed** [comment]
And on OSX system ? you don't use iptable ?

**Comment by ahpook** [comment]
No, the *host* does not use the iptables rules. The guests do. I'll try to clarify the docs, sorry that this is confusing.
