### ISSUE TITLE
Please use a different default domain than vagrant.dev

### ISSUE THREAD

**Issue by babilen** [phinze/landrush#118]
As `.dev` is one of the many new gTLDs introduced by ICANN it started to resolve to `127.0.53.53` (cf. #103) this domain should no longer be used by landrush.

See the following for further information:

* http://icannwiki.com/.dev
* https://www.icann.org/resources/pages/name-collision-2013-12-06-en#127.0.53.53 

A sensible alternative might be `.vagrant` or `.landrush`.

**Comment by njam** [comment]
People on the Internet recommend to use a real domain:
> Do not use an invented TLD. If ICANN were to delegate it, you would be in big trouble. Same thing if you merge with another organization which happens to use the same dummy TLD. That's why globally unique domain names are preferred.
http://serverfault.com/questions/17255/top-level-domain-domain-suffix-for-private-network

Personally I changed from `<project>.dev` to `<project>.dev.company.com`. It works nicely with landrush.

Not sure what would be good as a default though. Maybe register some domain à la `landrush.*`?

cc @ppp0

**Comment by ppp0** [comment]
Afaics `vagrant.dev` is used mostly for spec testing. As for the example (default) config, all requests for `vagrant.dev` would be handled locally.

Chrome and others started to complain about ICann name collisions, though, so may be switch to `vagrant.example.com`?

**Comment by babilen** [comment]
`vagrantup.com` comes to mind as well, but isn't in any way specific or indicative to landrush.

**Comment by KingCrunch** [comment]
Because (I guess) landrush is mostly used for local development I tend to use [`.localnet`](https://en.wikipedia.org/wiki/.localhost).

**Comment by babilen** [comment]
I really like `.test` and `.localhost`. That's a great suggestion and won't cause any collisions later on.

**Comment by ppp0** [comment]
Any of those sgtm - The important part being 
>Both are reserved as "never to be used as official TLD" via RFC2606

imho

**Comment by nawatts** [comment]
One issue with using `.localhost`:  Chrome now resolves `localhost` and `*.localhost` directly to `127.0.0.1` without going through OS X's resolver.

https://code.google.com/p/chromium/issues/detail?id=489973

**Comment by kyle-jennings** [comment]
I use `.loc` for all my custom sites.  Seems like a a good compromise as it is short for `.local/.localhost` and is also the familiar 3 character length.  Also makes it easy to do a quick find and replace from yoursite.dev to yoursite.loc in both config files and databases (WordPress for example)
