### ISSUE TITLE
Is it possible to do something like this so I don't need to enter my password when starting a instance?

### ISSUE THREAD

**Issue by BrianGilbert** [phinze/landrush#123]
The following blog explains how to add entries to the shudders file so that you don't need to enter your root password to start Vagrant when command is run for landrush to start that needs SUDO, this one appears to be targeted at NFS alone?

https://blog.jtclark.ca/2014/07/how-to-start-vagrant-boxes-without-a-password-on-your-mac/

What are the commands that get run at start and stop on a Mac?

**Comment by ahpook** [comment]
@BrianGilbert landrush doesn't normally need root privileges to start and stop. Can you make a gist of the commands and output leading up to the password prompt you're seeing?

**Comment by BrianGilbert** [comment]
confirmed it was NFS shares asking for PW
