### ISSUE TITLE
Allow multiple/additional hostnames

### ISSUE THREAD

**Issue by syssi** [phinze/landrush#128]
Our projects have multiple domains occasionally. Landrush handles just one hostname and its wildcard. An array for additional hostnames (f.e. config.landrush.additionalhostnames) would be nice.

Kind regards,

Sebastian

**Comment by njam** [comment]
This works form:
```
    config.landrush.host 'host1'
    config.landrush.host 'host2'
```

**Comment by syssi** [comment]
Awesome! :-) This helps  a lot!
