### ISSUE TITLE
Ping/dig and `vagrant landrush list` return different responses

### ISSUE THREAD

**Issue by nathanielks** [phinze/landrush#129]
Howdy, @phinze!

I'm running into a curious issue. I've got 4 vm's running currently:

| Hostname | IP |
| ------------- | ------------- |
| db-1.example.dev | 10.20.1.2 |
| gearman-1.example.dev | 10.20.1.3 |
| app-1.example.dev | 10.20.1.4 |
| example.dev | 10.20.1.5 |

Gearman isn't wanting to behave. If I ping or dig it from the host machine or any of the guests, it returns `10.20.1.5` when it should be `10.20.1.3`. `vagrant landrush list` returns it as the correct IP though. Any ideas?

| &nbsp; | &nbsp; |
| ------------- | ------------- |
| db-1.example.dev | 10.20.1.2 |
| 2.1.20.10.in-addr.arpa | db-1.example.dev |
| example.dev | 10.20.1.5 |
| 5.1.20.10.in-addr.arpa | example.dev |
| gearman-1.example.dev | 10.20.1.3 |
| 3.1.20.10.in-addr.arpa | gearman-1.example.dev |
| app-1.example.dev | 10.20.1.4 |
| 4.1.20.10.in-addr.arpa | app-1.example.dev |

**Comment by nathanielks** [comment]
The problem has gone away! ¯\_(ツ)_/¯

**Comment by ahpook** [comment]
awesomesauce! :+1:

**Comment by nathanielks** [comment]
I was relieved :relieved:
