### ISSUE TITLE
New Maintainers!

### ISSUE THREAD

**Issue by phinze** [phinze/landrush#139]
I have received word from several wonderful humans interested in helping pick up maintainer work on this project. Hooray!

Highlighting all of you so we can coordinate a bit:

 * @njam
 * @ahpook 
 * @strzibny 
 * @fh
 * @bexelbie

You're also all added as collaborators on the project as well. To be clear, nobody has actually accepted any responsibility here - this is just the initial broadcast to all those who expressed interest. Any of you can feel free to opt out at any point. :+1: 

As I mentioned, I'm pretty over allocated right now and have had precious little time for poor `landrush`. They say that the first step to finding a solution is admitting you have a problem. :grinning: 

I have no specific agenda for the project, so I'll leave it to you to talk about what's next. 

Here are some initial topic suggestions to kick things off:

 * Issue triage
 * Prioritizing important bugs / features 
 * Discussing whether or not to move the github repo to its own org - happy to do that if you folks would like

Welcome and thank you!

p.s. Anybody I missed who is interested in joining in just highlight me and I'll get you added as a collaborator and this discussion.

**Comment by fh** [comment]
Hey everyone, that looks like a decent group :)

I would suggest to first introduce some more tests and something like rubocop - with several maintainers, and (hopefully ;)) even more contributors, this might be a good thing to maintain a bit of a consistent style in the long run.

**Comment by strzibny** [comment]
Hi everyone,

I am here mainly because I wanted to see landrush run with libvirt and
possibly also on Windows in the future.

The first part is done and merged (libvirt support) and I would really like
to see a release soon with this change. It's important for people in our
organization.

Do you have anything else you would like to see for 0.19.0?

Otherwise I agree.

Best
Josef

**Comment by bexelbie** [comment]
Hi, sorry to be late to the reply party.  I am traveling right now and have inconsistent internet.  I am here because I would like to help leverage landrush with the Atomic Developer Bundle.

How do we want to handle PR Merges?

**Comment by ahpook** [comment]
thx @phinze - i started hacking on landrush because it scratched an itch i had and i wanted to dig into the guts of vagrant a bit more. i like going through the issues ppl raise and trying to help repro/troubleshoot problems.

**Comment by fh** [comment]
I would suggest to start labelling the issues in here, to be able to better triage things, and then maybe look into the most important bug and afterwards tag the next release?

My idea here would be to start with the labels `bug`, `feature-request`, `critical`, `needs-feedback`. `Bug` and `Critical` are applied after they have been verified by someone from the maintainer list above, `Needs-feedback` if there is something missing in the issue to be properly handled.

**Comment by njam** [comment]
Hello, happy New Year!

Agree with the labelling, triaging and releasing!

About PR merging I would suggest that we always ask at least one maintainer to do a review, and merge if everything is fine.

**Comment by bexelbie** [comment]
@njam I feel like we should have a 2 maintainer requirement.  However, I can't decide if that is because we need it or just because I am comfortable with it.  How does everyone else feel?

**Comment by njam** [comment]
yes, 2 maintainers sounds good to me
