### ISSUE TITLE
DNS wildcard issues after vagrant suspend and client restart

### ISSUE THREAD

**Issue by joshpangell** [phinze/landrush#163]
Hello,

I am using the landrush plugin to create a wildcard subdomain for my guest machine. This works correctly. However, once I `vagrant suspend` or `vagrant destroy`, the _real_ domain will no longer resolve. It will not `ping` or `dig` or anything, until `vagrant up` again. 

To be more clear; my main website domain `example.com` and `subdomain.example.com`, which are actually domains with real DNS entires, will resolve in the browser correctly while Vagrant is running. I have landrush configured to use the wildcard subdomain `local.example.com`, so that I can have `subdomain.local.example.com` resolve correctly. Once `vagrant suspend`, the domain `example.com` no longer resolves. 

Because I assumed I had something installed that was causing issues (VPN, dnsmasq, etc), I wiped the machine and did a fresh install of OS El Capitan. I installed Vagrant and nothing else. Same issue. 

Here is are the contents of the Vagrantfile:

```
Vagrant.configure("2") do |config|
  config.vm.box = "example"
  config.vm.box_url = "https://www.dropbox.com/s/kqym3o9no5mt89i/example?dl=1"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.hostname = "local.example.com"
  config.vm.synced_folder "../../release", "/var/www/example.com/release", :mount_options => ["dmode=775", "fmode=775"]

  # Landrush: https://github.com/phinze/landrush
  config.landrush.enabled = true
  config.landrush.tld = 'example.com'
  config.landrush.host 'local.example.com', '192.168.33.10'
end
```

To be fair, I have two other machines that are running this exact configuration without issue so it could be localized to this machine. However, I do not know how to debug further and would appreciate any pointers!

Thank you

**Comment by njam** [comment]
Landrush creates a file in `/etc/resolver` that makes OSX resolve the configured TLD through landrush (in your case `/etc/resolver/example.com`).

I think you should set the TLD to `local.example.com`.

**Comment by joshpangell** [comment]
Thanks for your response to this. Removing the file `/etc/resolver/example.com` worked! However, the local Vagrant box no longer resolved, unless it was destroyed and then re-up. And once that happened, the `/etc/resolver/example.com` file was re-added, causing the first issue to happen again.

However, the knowledge gleaned from this got me to a solution. Rather than using the real domain `example.com`, I simply used `example` in my config. That would mean that `http://local.example` will resolve correctly and will not cause any issues with the real domain's DNS.

For reference to anyone who may have this issue, here is my updated Vagrantfile. Note the removal of `.com` from the host:

```
Vagrant.configure("2") do |config|
  config.vm.box = "example"
  config.vm.box_url = "https://www.dropbox.com/s/kqym3o9no5mt89i/example?dl=1"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.hostname = "local.example"
  config.vm.synced_folder "../../release", "/var/www/example.com/release", :mount_options => ["dmode=775", "fmode=775"]

  # Landrush: https://github.com/phinze/landrush
  config.landrush.enabled = true
  config.landrush.tld = 'example'
  config.landrush.host 'local.example', '192.168.33.10'
end
```
