### ISSUE TITLE
Hook on machine action reload

### ISSUE THREAD

**Issue by nathanielks** [phinze/landrush#92]
Currently you have to run `vagrant halt/destroy` and then `vagrant up` in order for landrush to configure itself. Could it run on reload as well?

**Comment by djmittens** [comment]
There has been several issues open for this particular problem.
#15
#9

**Comment by phinze** [comment]
Fixed in #101 and released shortly, hooray! :dancers:

**Comment by nathanielks** [comment]
Woot woot! Thanks @phinze :beers:
